### ISSUE TITLE
Update User not accepting PUT requests

### ISSUE THREAD

**Issue by marksmall** [astrosat/django-astrosat-users#10]
## Checklist

- [ ] Is this issue linked to an **Epic** issue?
- [ ] Have you linked each commit to their issue e.g. First line should contain text like `IssueID #123 - Update dependencies for front-end:`. The important bit is the start `IssueID #123`, this will create a reference in the issue, to the commit.
- [ ] Have you set **Reviewers**, **labels** and **Milestone**?

## Describe the bug

When **updating** a user's profile, we will want to use `PUT` requests. Currently it seems this is not being accepted. As an example of how this would work, I've created a client-side form that allows the user to add a `first_name` and `last_name`, but requests are failing. Changing the method to `POST` acts like we are trying to create a new user and complains that the `user already exists`.

**Comment by allynt** [comment]
Done as part of #23.
