### ISSUE TITLE
registering with already used username response

### ISSUE THREAD

**Issue by marksmall** [astrosat/django-astrosat-users#11]
## Checklist

- [ ] Is this issue linked to an **Epic** issue?
- [ ] Have you linked each commit to their issue e.g. First line should contain text like `IssueID #123 - Update dependencies for front-end:`. The important bit is the start `IssueID #123`, this will create a reference in the issue, to the commit.
- [ ] Have you set **Reviewers**, **labels** and **Milestone**?

## Describe the bug

When I try to register with an already registered username (in our case the email address) I get 2 error messages, one stating the **username** already exists and the second about the **email** already registered. Since we are going to use the **email** as the username, we should only have one of these error messages, don't really care which.

**Comment by allynt** [comment]
setting
```
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
```
fixed this.
