### ISSUE TITLE
Add extra details to customer

### ISSUE THREAD

**Issue by marksmall** [astrosat/django-astrosat-users#51]
https://app.zeplin.io/project/5dbc13c25fdea783b88ab405/screen/5ec7d39dca0aac29ff34bd3d

The designs suggest there are some missing details for a customer, namely:

- Country
- Address
- Postcode
- VAT number (**Still to be signed-off and may be removed**)
- Payment contact details (**Still to be signed-off and may be removed**)
- Payment account id (**Still to be signed-off and may be removed**)

For now, we will only add the those where agreement exists they should be used and leave the others until a decision has been made.

**Comment by marksmall** [comment]
So this seems fairly straight-forward, add these fields to the Customer `model` and serializer/admin, so they can be used.

**Comment by allynt** [comment]
https://app.zeplin.io/project/5dbc13c25fdea783b88ab405/screen/5ec7d39dca0aac29ff34bd3d
